#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from kr_sources_config import DEFAULT_SOURCE_FILES, OUTPUT_FILE


def read_tickers(path: str) -> list[str]:
    p = Path(path)
    if not p.exists():
        return []
    out: list[str] = []
    for raw in p.read_text(encoding="utf-8", errors="ignore").splitlines():
        s = raw.split("#", 1)[0].strip()
        if not s:
            continue
        out.append(s)
    return out


def union_ordered(paths: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for path in paths:
        for t in read_tickers(path):
            if t not in seen:
                seen.add(t)
                out.append(t)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("sources", nargs="*", help="Override source files")
    ap.add_argument("--out", default=OUTPUT_FILE)
    args = ap.parse_args()

    sources = args.sources or DEFAULT_SOURCE_FILES
    merged = union_ordered(sources)
    header = [
        "# tickers_korea.txt",
        "# Auto-generated by kr_sync_tickers.py",
        "# sources=" + ", ".join(sources),
        "",
    ]
    Path(args.out).write_text("\n".join(header + merged) + "\n", encoding="utf-8")
    print(f"Saved: {args.out} (count={len(merged)})")
    for src in sources:
        print(f" - {src}: {len(read_tickers(src))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
