#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""run_pipeline_v3_ab_NOFILTER.py

Same idea as your A/B pipeline, but:
- NO prefilter step
- Always uses tickers.txt (generated by sync) as the universe for update
- candidates.txt is still used as stage-1 shortlist (top N)

Usage:
  python run_pipeline_v3_ab_NOFILTER.py --break-mode a --intraday --hold-bars 3 --top 10 --max-2x 5 --pdf
  python run_pipeline_v3_ab_NOFILTER.py   # will prompt break-mode if not provided
"""

from __future__ import annotations
import argparse, subprocess, sys
from pathlib import Path

def sh(cmd: list[str]) -> int:
    print("\n$ " + " ".join(cmd))
    return subprocess.call(cmd)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--break-mode", choices=["a","b","c"], default=None, help="a=60d-high, b=pattern, c=entry-rank loose")
    ap.add_argument("--intraday", action="store_true")
    ap.add_argument("--hold-bars", type=int, default=3)
    ap.add_argument("--top", type=int, default=10)
    ap.add_argument("--max-2x", type=int, default=5)
    ap.add_argument("--pdf", action="store_true")
    ap.add_argument("--refresh-bad", action="store_true", help="Revalidate missing tickers (slow)")
    ap.add_argument("--entry-max-chase", type=float, default=1.0, help="Only used in break-mode c (loose entry rank)")
    args = ap.parse_args()

    mode = args.break_mode
    if not mode:
        try:
            mode = input("Select break-mode (A=60d high, B=pattern neckline/triangle, C=entry-rank loose) [B]: ").strip().lower() or "b"
        except KeyboardInterrupt:
            return 130
        if mode not in ("a","b","c"):
            mode = "b"
    print(f"[mode] break-mode={mode.upper()}")

    py = sys.executable

    # 0) sync tickers.txt
    if Path("sync_tickers_txt.py").exists():
        sh([py, "sync_tickers_txt.py"])
    else:
        print("[warn] sync_tickers_txt.py not found; skipping sync")

    # 1) update premarket auto (NO prefilter)
    upd = "update_premarket_yf_auto_fast_v3.py" if Path("update_premarket_yf_auto_fast_v3.py").exists() else "update_premarket_yf_auto_fast_v2.py"
    if not Path(upd).exists():
        print(f"[error] missing {upd}")
        return 2
    cmd = [py, upd, "--universe-file", "tickers.txt"]
    if args.refresh_bad:
        cmd.append("--refresh-bad")
    sh(cmd)

    # 2) stage-1 candidates
    if mode == "b":
        cand = "bulkowski_scan_from_debugcsv_pattern_v3.py"
        if not Path(cand).exists():
            cand = "bulkowski_scan_from_debugcsv_pattern_v2.py"
        if not Path(cand).exists():
            print("[error] pattern candidate script missing")
            return 2
        sh([py, cand, "--top", str(args.top), "--out", "candidates.txt", "--max-2x", str(args.max_2x),
            "--break-mode", "b", "--groups", "tickers_core,tickers_leverage2x,finviz_manual,macro_watch_yahoo"])
    elif mode == "a":
        cand = "bulkowski_scan_from_debugcsv_strict_v5_ranked.py" if Path("bulkowski_scan_from_debugcsv_strict_v5_ranked.py").exists() else "bulkowski_scan_from_debugcsv_strict_v4.py"
        if not Path(cand).exists():
            print("[error] strict candidate script missing")
            return 2
        sh([py, cand, "--top", str(args.top), "--out", "candidates.txt", "--max-2x", str(args.max_2x),
            "--break-mode", "a", "--groups", "tickers_core,tickers_leverage2x,finviz_manual,macro_watch_yahoo"])
    else:
        if not Path("make_entry_rank_a_loose.py").exists():
            print("[error] make_entry_rank_a_loose.py missing for break-mode c")
            return 2
        sh([py, "make_entry_rank_a_loose.py", "--top", str(args.top), "--out", "candidates.txt", "--max-2x", str(args.max_2x),
            "--max-chase", str(args.entry_max_chase)])

    # 3) manual prices (for candidates)
    if Path("make_premarket_manual_5.py").exists():
        sh([py, "make_premarket_manual_5.py"])
    else:
        print("[warn] make_premarket_manual_5.py not found; skipping manual entry")

    # 4) merge
    if Path("merge_premarkets_v2.py").exists():
        sh([py, "merge_premarkets_v2.py"])
    elif Path("merge_premarkets.py").exists():
        sh([py, "merge_premarkets.py"])
    else:
        print("[error] merge_premarkets(_v2).py missing")
        return 2

    # 5) strict scan on candidates.txt
    scan = "scan_candidates_v2_safe_v7_strict_v2d.py"
    if not Path(scan).exists():
        scan = "scan_candidates_v2_safe_v7_strict_v2b.py"
    if not Path(scan).exists():
        print("[error] strict scan script missing")
        return 2
    scmd = [py, scan, "--break-mode", mode]
    if args.intraday:
        scmd += ["--intraday", "--hold-bars", str(args.hold_bars)]
    sh(scmd)

    # 6) buy report
    rep = "make_buy_report_v9.py"
    if Path(rep).exists():
        rcmd = [py, rep, "--top", str(max(args.top, 15)), "--xlsx"]
        if args.pdf:
            rcmd.append("--pdf")
        sh(rcmd)
    else:
        print("[warn] make_buy_report_v9.py not found; skipping buy report")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
